[package]
name = "rustsbi-hpm"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/hpmicro/rustsbi-hpm"

[dependencies]
hpm-metapac = { path = "../hpm-metapac" }
hpm-hal = { path = "../hpmicro-hal", default-features = false }
rustsbi = { version = "0.4.0", features = ["machine"] }
sbi-spec = { version = "0.0.7", features = ["legacy"] }
hpm-rt = { git = "https://github.com/hpm-rs/hpm-rt.git", rev = "f9dd2f2122630ebfa8d9b96f539aba8be1c92784" }

riscv = "0.10"
spin = "0.12"
fast-trap = { git = "https://github.com/rustsbi/fast-trap.git", features = [
    "riscv-m",
] }
riscv-decode = "0.2.2"

embedded-hal = "1.0"
embedded-hal-nb = "1.0.0"
nb = "1.1.0"

[build-dependencies]
hpm-rt = { git = "https://github.com/hpm-rs/hpm-rt.git", rev = "f9dd2f2122630ebfa8d9b96f539aba8be1c92784" }

[features]
default = []
hpm6360evk = ["hpm-metapac/hpm6360", "hpm-hal/hpm6360", "hpm-hal/time"]
hpm6750evkmini = ["hpm-metapac/hpm6750", "hpm-hal/hpm6750", "hpm-hal/time"]
ram = []
flash = []
sdram-rw-test = []

[profile.release]
debug = true

[patch.crates-io]
riscv-rt = { git = "https://github.com/hpm-rs/hpm-rt.git", rev = "f9dd2f2122630ebfa8d9b96f539aba8be1c92784", package = "hpm-rt" }

[patch."https://github.com/hpmicro-rs/hpm-metapac.git"]
hpm-metapac = { path = "../hpm-metapac" }
